services:
  db-postgres:
    image: postgres:16.0-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "on-failure: 5"
#    read_only: true
    volumes:
      - vol-db-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: render-be
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/secret-db-postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    secrets:
      - secret-db-postgres

  configurator:
    build:
      context: configurator
    image: gis/configurator
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "on-failure: 5"
#    read_only: true
    command: [ "java", "-jar", "application.jar", "--spring.profiles.active=docker,native" ]
    mem_limit: 512m
    secrets:
      - secret-configurator-pwd

  discovery:
    build:
      context: discovery
    image: gis/discovery
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "on-failure: 5"
#    read_only: true
    command: [ "java", "-jar", "application.jar", "--spring.profiles.active=docker" ]
    mem_limit: 512m
    depends_on:
      configurator:
        condition: service_healthy

  gateway:
    build:
      context: gateway
    image: gis/gateway
    command: [ "java", "-jar", "application.jar", "--spring.profiles.active=docker" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "https://localhost:8443/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "on-failure: 5"
#    read_only: true
    mem_limit: 512m
    depends_on:
      configurator:
        condition: service_healthy
      discovery:
        condition: service_healthy
    secrets:
      - secret-gateway-cert
      - secret-gateway-ca-pass
    ports:
      - "8443:8443"

  render-be:
    build:
      context: render-be
    image: gis/render-be
    command: [ "java", "-jar", "application.jar", "--spring.profiles.active=docker" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: "on-failure: 5"
#    read_only: true
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/secret-db-postgres
    mem_limit: 512m
    depends_on:
      configurator:
        condition: service_healthy
      discovery:
        condition: service_healthy
      db-postgres:
        condition: service_healthy
    secrets:
      - secret-db-postgres

secrets:
  secret-db-postgres:
    file: ./secrets/db-postgres/root_pass
  secret-configurator-pwd:
    file: ./secrets/configurator/service_pass
  secret-gateway-cert:
    file: ./secrets/gateway/gateway.p12
  secret-gateway-ca-pass:
    file: ./secrets/gateway/ca_pass

volumes:
  vol-db-postgres:
