spring.config.import: "optional:configserver:"

spring:
  application.name: render-be
  cloud:
    #    config:
    #      uri: http://localhost:8888
    #      fail-fast: true
    #      retry:
    #        initialInterval: 3000
    #        multiplier: 1.3
    #        maxInterval: 10000
    #        maxAttempts: 20
    password: changeMe
    username: user

---
spring:
  config.activate.on-profile: docker
  cloud.config.uri: http://configurator:8888
